// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obijblotjvjggoxetfxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9iaWpibG90anZqZ2dveGV0ZnhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNjgxNjEsImV4cCI6MjA1ODg0NDE2MX0.nCykSv0SSmpnYsyv84MHQGdsTczHwSCkOTNzDCedPgU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);